### ISSUE TITLE
Space key goes back to case selections screen

### ISSUE THREAD

**Issue by ericpignet** [Dave2ooo/F2LTrainer-Legacy#24]
Hi,
I've just discovered your F2L trainer and it's great!
One thing which is a bit annoying is that when you go to Train mode, the ''Select cases" button has focus - at least for me - so when you press Space bar, it goes back to case selection.
You need to manually click on anywhere else in the screen to make sure 'Select cases' button does not have focus, then you can use Space bar to go to next scramble.
Thanks,
Eric

**Comment by Dave2ooo** [comment]
Hi Eric,
thanks for submitting this issue.
A simple "btn.blur()" line in Javascript resolved the issue.
This is now implemented in the latest version.

Thanks again,
David
